config/routes.rb
Rails.application.routes.draw do
  # ============== deviseのルーティング ==================
  devise_for :admins,
    path: :admin,
    controllers: {
      sessions: 'admin/devise/sessions',
      passwords: 'admin/devise/passwords',
      registrations: 'admin/devise/registrations',
    }
  devise_for :users,
    controllers: {
      sessions: 'public/devise/sessions',
      passwords: 'public/devise/passwords',
      registrations: 'public/devise/registrations',
    }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/devise/sessions#guest_sign_in'
  end
  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/devise/sessions#guest_sign_in'
  end

  # ========= ユーザー(public)のルーティング ================
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'premium' => 'homes#premium'

    resources :form_inquiries, only: [:index, :new, :create]
    get 'form_inquiries/complete' => 'form_inquiries#complete', as: 'form_inquiry_complete'
    resource :chats, only: [:show, :create]

    get 'post_recipes/searches' => 'searches#index'
    get 'post_recipes/rankings' => 'rankings#index'
    resources :post_recipes do
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
      resource :saved_recipes, only: [:create, :destroy]
    end

    get 'users/quit_confirm' => 'users#quit_confirm'
    patch 'users/quit' => 'users#quit'
    patch 'users/cancel_premium' => 'users#cancel_premium'
    resources :users, only: [:show, :edit, :update] do
      post 'relationships/:page_user_id' => 'relationships#create', as: 'add_follow'
      delete 'relationships/:page_user_id' => 'relationships#destroy', as: 'remove_follow'
      get :follows, on: :member
    end

    resource :premiums, only: [:update]
    get 'premiums/payment' => 'premiums#payment'
    get 'premiums/complete' => 'premiums#complete'
  end

  # ========= 管理者(admin)のルーティング ================
  namespace :admin do
    root to: 'homes#top'
    resources :post_recipes, only: [:index, :show, :destroy]
    resources :form_inquiries, only: [:index, :show, :update]
    resources :chats, only: [:index, :show, :create]
    resources :users, only: [:index, :show, :edit, :update]
  end
end

app/helpers/admin/recipes_helper.rb
module Admin::RecipesHelper
end

app/views/admin/recipes/index.html.erb
<div class="container">

  <div class="row">
    <h3 class="admin-page-title mx-auto mt-5 py-2 pl-4">レシピ一覧</h3>
  </div>

  <div class="row">
    <div class="col-md-4 offset-md-8">
      <h6 class="text-right mr-5 jp-font">レシピ数：<%= @recipe_count %>件</h6>
    </div>
  </div>

  <div class="row">
    <table style="width: 80%" class="table table-borderless mx-auto">
      <% @recipes.each do |recipe| %>
        <tr class="mt-5 border-bottom">
          <td style="width: 5%" class="text-center">
            <%= link_to (attachment_image_tag recipe, :recipe_image, :fill, 70, 70, format: 'jpeg', class: 'rounded-circle'), admin_recipe_path(recipe.id) %>
          </td>
          <td style="width: 35%">
            <u><%= link_to recipe.title, admin_recipe_path(recipe.id) %><br /></u>
            <p class="mt-2"><%= recipe.introduction %></p>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="row">
    <div class="mx-auto mt-4 mb-5">
    <%= paginate @recipes %>
    </div>
  </div>
</div>