config/routes.rb
Rails.application.routes.draw do
  # ============== deviseのルーティング ==================
  devise_for :admins,
    path: :admin,
    controllers: {
      sessions: 'admin/devise/sessions',
      passwords: 'admin/devise/passwords',
      registrations: 'admin/devise/registrations',
    }
  devise_for :users,
    controllers: {
      sessions: 'public/devise/sessions',
      passwords: 'public/devise/passwords',
      registrations: 'public/devise/registrations',
    }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/devise/sessions#guest_sign_in'
  end
  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/devise/sessions#guest_sign_in'
  end

  # ========= ユーザー(public)のルーティング ================
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'premium' => 'homes#premium'

    resources :form_inquiries, only: [:index, :new, :create]
    get 'form_inquiries/complete' => 'form_inquiries#complete', as: 'form_inquiry_complete'
    resource :chats, only: [:show, :create]

    get 'post_recipes/searches' => 'searches#index'
    get 'post_recipes/rankings' => 'rankings#index'
    resources :post_recipes do
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
      resource :saved_recipes, only: [:create, :destroy]
    end

    get 'users/quit_confirm' => 'users#quit_confirm'
    patch 'users/quit' => 'users#quit'
    patch 'users/cancel_premium' => 'users#cancel_premium'
    resources :users, only: [:show, :edit, :update] do
      post 'relationships/:page_user_id' => 'relationships#create', as: 'add_follow'
      delete 'relationships/:page_user_id' => 'relationships#destroy', as: 'remove_follow'
      get :follows, on: :member
    end

    resource :premiums, only: [:update]
    get 'premiums/payment' => 'premiums#payment'
    get 'premiums/complete' => 'premiums#complete'
  end

  # ========= 管理者(admin)のルーティング ================
  namespace :admin do
    root to: 'homes#top'
    resources :post_recipes, only: [:index, :show, :destroy]
    resources :form_inquiries, only: [:index, :show, :update]
    resources :chats, only: [:index, :show, :create]
    resources :users, only: [:index, :show, :edit, :update]
  end
end

app/views/shared/_comments.html.erb
<!--------- コメント一覧 --------->

<table id="comments-list" style="width: 80%" class="table table-borderless mx-auto mt-2">
  <% post_recipe.comments.each do |comment| %>
  <tr class="mt-2">
    <td style="width: 10%" class="align-middle text-center">
      <%= attachment_image_tag comment.user, :profile_image, :fill, 300, 300, format: 'jpg', class:'mx-auto rounded-circle', fallback: 'no_profile_image.jpg', size:'60x60' %><br />
      <p style='font-size: 12px' class="mt-2 mb-0"><%= comment.user.name %></p>
    </td>
    <td style="width: 70%" class="text-wrap align-middle"><%= comment.comment %></td>

    <% if comment.user == current_user %>
    <td style="width: 20%" class="align-middle">
      <%= link_to "削除", post_recipe_comment_path(comment.post_recipe.id, comment.id), remote: true, class: 'btn btn-sm btn-danger', method: :delete %>
    </td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/shared/_like_save_buttons.html.erb
<!---------- いいねボタンとレシピ保存ボタンの部分テンプレート ---------->

<div id="like-save-buttons">
  <div class="row">
    <div class="col-6 offset-6 col-md-5 offset-md-7 text-right d-flex">

    <% if user_signed_in? %>
      <!--いいねボタン-->
      <% if post_recipe.liked_by?(current_user) %>
        <%= link_to post_recipe_likes_path(post_recipe), method: :delete, remote: true, class:'text-danger like-btn ml-5' do %>
          <span class="fas fa-heart text-danger"></span>
          <%= post_recipe.likes.count %>
        <% end %>
      <% else %>
        <%= link_to post_recipe_likes_path(post_recipe), method: :post, remote: true, class:'text-danger like-btn ml-5' do %>
          <span class="far fa-heart like-button text-danger"></span>
          <%= post_recipe.likes.count %>
        <% end %>
      <% end %>
      <!--レシピお気に入り保存ボタン-->
      <% if post_recipe.saved_by?(current_user) %>
        <%= link_to " SAVED", post_recipe_saved_recipes_path(post_recipe), method: :delete, remote: true, class:'text-secondary ml-3 pt-1 fas fa-bookmark' %>
      <% else %>
        <%= link_to " SAVE", post_recipe_saved_recipes_path(post_recipe), method: :post, remote: true, class:'text-secondary ml-3 pt-1 far fa-bookmark' %>
      <% end %>

    <!--非ログインユーザー及び管理者用の非活性ボタン-->
    <% else %>
        <span class="far fa-heart text-danger pt-1 ml-5"></span>
        <p class="text-danger"><%= post_recipe.likes.count %></p>
        <p class="far fa-bookmark text-secondary ml-4 pt-1">保存</p>
    <% end %>
    </div>
  </div>
</div>

app/views/shared/_recipe_show.html.erb
<!---------- レシピ詳細 -------------->

  <div class="row">
    <div class="mx-auto mt-5">
      <h2 class="jp-font-classic px-3"><%= post_recipe.title %></h2>
    </div>
  </div>

  <div class="row">
    <div class="mx-auto">
      <p class="jp-font-classic">by
      <% if admin_signed_in? %>
        <%= link_to "#{post_recipe.user.name}", admin_user_path(post_recipe.user.id), class:'font-color-green' %></p>
      <% else %>
        <%= link_to "#{post_recipe.user.name}", user_path(post_recipe.user.id), class:'font-color-green' %></p>
      <% end %>
    </div>
  </div>

  <div class="row mt-2 recipe-img">
    <%= ix_image_tag(post_recipe.post_recipe_image.path, url_params: { w: 550, h: 400, fit: 'crop' }, tag_options: { class: 'mx-auto' }) %>
  </div>

  <div class="row my-4">
    <%= render partial: 'shared/veg_type_icons', locals: { post_recipe: post_recipe} %>
  </div>

  <div class="row mt-4 mb-3">
    <p style="width: 450px" class="mx-auto text-wrap text-center px-3"><%= post_recipe.introduction %></p>
  </div>

  <!--いいねボタンとレシピ保存ボタンの部分テンプレートを表示-->
  <% if post_recipe.is_draft == false %>
    <%= render partial: '/shared/like_save_buttons', locals: { post_recipe: post_recipe } %>
  <% end %>

  <div class="row mt-4">
    <table style="width: 60%" class="table table-borderless mx-auto">
      <thead class="border-bottom">
        <th class="d-flex pb-0 mb-2">
          <h5 class="mb-0 jp-font-classic">材料</h5>
          <p class="mb-0 ml-1 pt-1 jp-font-classic">（<%= post_recipe.serving %>人前）</p>
        </th>
        <th></th>
      </thead>
      <tbody>
        <% post_recipe.ingredients.each do |ingredient| %>
        <tr>
          <td style="width: 45%" class='pt-4 pl-4'><%= ingredient.name %></td>
          <td style="width: 10%" class='pt-4'><%= ingredient.amount %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="row mx-auto mt-5">
    <table style="width: 65%" class="table table-borderless mx-auto">
      <thead class="page-heading-pink">
        <th colspan="2" class="py-1">
          <h5 class="jp-font-classic text-white text-center mb-0">つくり方</h5>
        </th>
      </thead>
      <tbody>
        <% step_num = 0 %>
        <% post_recipe.procedures.each do |procedure| %>
        <tr class="ml-2">
          <td style='width: 5%' class='text-center font-weight-bold pt-3'><%= step_num += 1 %>)</td>
          <td style='width: 50%' class="text-wrap pt-3"><%= procedure.body %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

<div class="row mt-5">
  <div class="mx-auto">
    <h5 class="mb-0 en-font-pop font-color-green">Comments</h5>
  </div>
</div>
<div class="row">
  <div class="col-8 offset-3 offset-sm-2">
    <%= render partial: '/shared/comments', locals: { post_recipe: post_recipe } %>
  </div>
</div>

app/views/shared/_veg_type_icons.html.erb
<!--レシピカードに表示する使用食材のアイコン -->

 <div class="d-flex mx-auto pt-1">
    <% case post_recipe.veg_type
    when "pesco" %>
      <i class="fas fa-seedling text-success"></i>
      <i class="fas fa-fish pl-2 text-primary"></i>
      <i class="fas fa-egg pl-2"></i>
      <i class="fas fa-cheese pl-2 text-warning"></i>
    <% when "lacto_ovo" %>
      <i class="fas fa-seedling text-success"></i>
      <i class="fas fa-egg pl-2"></i>
      <i class="fas fa-cheese pl-2 text-warning"></i>
    <% when "lacto" %>
      <i class="fas fa-seedling text-success"></i>
      <i class="fas fa-cheese pl-2 text-warning"></i>
    <% when "ovo" %>
      <i class="fas fa-seedling text-success"></i>
      <i class="fas fa-egg pl-2"></i>
    <% else %>
      <i class="fas fa-seedling text-success"></i>
    <% end %>
  </div>