config/routes.rb
Rails.application.routes.draw do
  # ============== deviseのルーティング ==================
  devise_for :admins,
    path: :admin,
    controllers: {
      sessions: 'admin/devise/sessions',
      passwords: 'admin/devise/passwords',
      registrations: 'admin/devise/registrations',
    }
  devise_for :users,
    controllers: {
      sessions: 'public/devise/sessions',
      passwords: 'public/devise/passwords',
      registrations: 'public/devise/registrations',
    }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/devise/sessions#guest_sign_in'
  end
  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/devise/sessions#guest_sign_in'
  end

  # ========= ユーザー(public)のルーティング ================
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'premium' => 'homes#premium'

    resources :form_inquiries, only: [:index, :new, :create]
    get 'form_inquiries/complete' => 'form_inquiries#complete', as: 'form_inquiry_complete'
    resource :chats, only: [:show, :create]

    get 'post_recipes/searches' => 'searches#index'
    get 'post_recipes/rankings' => 'rankings#index'
    resources :post_recipes do
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
      resource :saved_recipes, only: [:create, :destroy]
    end

    get 'users/quit_confirm' => 'users#quit_confirm'
    patch 'users/quit' => 'users#quit'
    patch 'users/cancel_premium' => 'users#cancel_premium'
    resources :users, only: [:show, :edit, :update] do
      post 'relationships/:page_user_id' => 'relationships#create', as: 'add_follow'
      delete 'relationships/:page_user_id' => 'relationships#destroy', as: 'remove_follow'
      get :follows, on: :member
    end

    resource :premiums, only: [:update]
    get 'premiums/payment' => 'premiums#payment'
    get 'premiums/complete' => 'premiums#complete'
  end

  # ========= 管理者(admin)のルーティング ================
  namespace :admin do
    root to: 'homes#top'
    resources :post_recipes, only: [:index, :show, :destroy]
    resources :form_inquiries, only: [:index, :show, :update]
    resources :chats, only: [:index, :show, :create]
    resources :users, only: [:index, :show, :edit, :update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :form_inquiries, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_one :chat_room, dependent: :destroy
  has_many :histories, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :saved_recipes, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :followers, through: :passive_relationships, source: :following

  validates :introduction, length: { maximum: 40 }
  with_options presence: true do
    validates :name
    validates :email
  end

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  attachment :profile_image

  def is_paid_to_sring
    if is_paid == true
      "プレミアム（有料）"
    elsif is_paid == false
      "スタンダード（無料）"
    end
  end

  def is_deleted_to_sring
    if is_deleted == true
      "退会済"
    elsif is_deleted == false
      "有効"
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト会員"
      user.introduction = "こちらはゲスト・アカウント（会員）です。会員の機能を利用することができます。"
      user.id = 1
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_user, only: [:show, :edit, :update]
  before_action :prohibit_guest_quit, only: [:update]

  def index
    @users = User.page(params[:page])
    @user_count = User.count
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      # 会員を退会にする場合
      if @user.is_deleted == true
        @user.post_recipes.update(is_draft: true)
        @user.comments.destroy_all
        @user.histories.destroy_all
        @user.likes.destroy_all
        @user.saved_recipes.destroy_all
        @user.active_relationships.destroy_all
        @user.passive_relationships.destroy_all
      # 会員を有効にする場合
      else
        @user.post_recipes.update(is_draft: false)
      end
      redirect_to admin_user_path(@user), notice: "会員ステータスを更新しました"
    else
      render :edit, alert: "会員ステータスを更新できませんでした"
    end
  end

  private

  def user_params
    params.require(:user).permit(:is_deleted)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def prohibit_guest_quit
    if @user.id == 1
      redirect_to admin_users_path, alert: "ゲスト会員は退会できません。"
    end
  end
end

app/views/admin/users/edit.html.erb
<!---------------- 管理者：会員編集 ------------------>
<div style="height: 650px", class="d-flex align-items-center">
  <div class="container">

    <u><h3 class="jp-font-classic">会員ステータスの変更</h3></u>

    <%= form_with model: @user, url: admin_user_path(@user.id), method: :PATCH, local:true do |f| %>
    <table style='width:75%' class="table mt-5">
      <tr>
        <td style="width:25%" class="font-weight-bold">ユーザー名</td>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <td style="width:25%" class="font-weight-bold">自己紹介</td>
        <td><%= @user.introduction %></td>
      </tr>
      <tr>
        <td style="width:25%" class="font-weight-bold">メールアドレス</td>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <td style="width:25%", class="font-weight-bold">加入プラン</td>
        <td class="ml-3"><%= @user.is_paid_to_sring %></td>
      </tr>
      <tr class="form-group text-danger">
        <td style="width:25%" class="font-weight-bold text-danger">会員ステータス</td>
        <td>
          <%= f.radio_button :is_deleted, :false %>
          <%= f.label :is_deleted, "有効", class:' text-danger' %><br />
          <%= f.radio_button :is_deleted, :true %>
          <%= f.label :is_deleted, "退会済", class:' text-danger' %>
        </td>
      </tr>
    </table>

    <div class="d-flex mt-4 ml-2">
      <%= f.submit '会員ステータスを変更', class:'btn btn-sm btn-danger py-0', data: { confirm: "本当に#{@user.name}さんの会員ステータスを変更しますか？" } %>
      <%= link_to "戻る", admin_user_path(@user.id), class: 'btn btn-sm btn-secondary ml-4' %>
    </div>
    <% end %>

  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <h3 style='width: 100%' class="page-heading-pink mx-auto mt-5 py-1 text-center">会員一覧</h3>
  </div>

  <div class="row mb-3">
    <div class="col-6 offset-6 text-right">
      <h6 class="text-right mr-5 jp-font">会員数：<%= @user_count %>名</h6>
    </div>
  </div>

  <div class="row">
    <table style="width: 95%" class="table table-borderless mx-auto">
      <% @users.each do |user| %>
        <tr class="mt-5 border-bottom">
          <td style="width: 5%" class='text-right'>
            <%= link_to (attachment_image_tag user, :profile_image, :fill, 150, 150, format: 'jpg', fallback: "no_profile_image.jpg", size:'40x40', class:'rounded-circle'), admin_user_path(user.id) %>
          </td>
          <td style="width: 15%" class='px-1 py-4 text-center'>
            <u><%= link_to user.name, admin_user_path(user.id) %></u>
          </td>
          <td style="width: 17%; font-size: 12px" class="py-0 px-1 align-middle text-center">
            <%= user.is_paid_to_sring %>
          </td>
          <td style="width: 8%" class="py-0 px-1 align-middle text-center">
            <% if user.is_deleted == false %>
              <p class="active_color mb-0"><%= user.is_deleted_to_sring %></p>
            <% else %>
              <p class="inactive_color mb-0"><%= user.is_deleted_to_sring %></p>
            <% end %>
          </td>
          <td style="width: 10%" class="py-0 px-1 align-middle text-center">
            <%= link_to "CHAT", admin_chat_path(user), class: 'btn btn-sm btn-outline-secondary', style: 'font-size: 13px' %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="row">
    <div class="mx-auto mt-4 mb-5">
    <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<!---------------- 管理者：会員詳細 ------------------>

<div style="height: 650px", class="d-flex align-items-center">
  <div class="container">
    <u><h3 class="jp-font-classic"><%= @user.name %>さんの会員情報</h3></u>

    <table style='width:75%' class="table mt-5">
      <tr>
        <td style="width:25%", class="font-weight-bold">ユーザー名</td>
        <td class="ml-3"><%= @user.name %></td>
      </tr>
      <tr>
        <td style="width:25%", class="font-weight-bold">自己紹介</td>
        <td class="ml-3"><%= @user.introduction %></td>
      </tr>
      <tr>
        <td style="width:25%", class="font-weight-bold">メールアドレス</td>
        <td class="ml-3"><%= @user.email %></td>
      </tr>
      <tr>
        <td style="width:25%", class="font-weight-bold">加入プラン</td>
        <td class="ml-3"><%= @user.is_paid_to_sring %></td>
      </tr>
      <tr>
        <td style="width:25%", class="font-weight-bold">会員ステータス</td>
          <% if @user.is_deleted == false %>
            <td class="ml-3 active_color"><%= @user.is_deleted_to_sring %></td>
          <% else %>
            <td class="ml-3 inactive_color"><%= @user.is_deleted_to_sring %></td>
          <% end %>
      </tr>
    </table>

    <div class="d-flex mt-5 ml-2">
      <%= link_to "会員ステータスを編集", edit_admin_user_path(@user.id), class: 'btn btn-sm btn-outline-danger' %>
      <%= link_to "戻る", admin_users_path, class: 'btn btn-sm btn-secondary ml-4' %>
    </div>

  </div>
</div>