config/routes.rb
Rails.application.routes.draw do
  # ============== deviseのルーティング ==================
  devise_for :admins,
    path: :admin,
    controllers: {
      sessions: 'admin/devise/sessions',
      passwords: 'admin/devise/passwords',
      registrations: 'admin/devise/registrations',
    }
  devise_for :users,
    controllers: {
      sessions: 'public/devise/sessions',
      passwords: 'public/devise/passwords',
      registrations: 'public/devise/registrations',
    }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/devise/sessions#guest_sign_in'
  end
  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/devise/sessions#guest_sign_in'
  end

  # ========= ユーザー(public)のルーティング ================
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'premium' => 'homes#premium'

    resources :form_inquiries, only: [:index, :new, :create]
    get 'form_inquiries/complete' => 'form_inquiries#complete', as: 'form_inquiry_complete'
    resource :chats, only: [:show, :create]

    get 'post_recipes/searches' => 'searches#index'
    get 'post_recipes/rankings' => 'rankings#index'
    resources :post_recipes do
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
      resource :saved_recipes, only: [:create, :destroy]
    end

    get 'users/quit_confirm' => 'users#quit_confirm'
    patch 'users/quit' => 'users#quit'
    patch 'users/cancel_premium' => 'users#cancel_premium'
    resources :users, only: [:show, :edit, :update] do
      post 'relationships/:page_user_id' => 'relationships#create', as: 'add_follow'
      delete 'relationships/:page_user_id' => 'relationships#destroy', as: 'remove_follow'
      get :follows, on: :member
    end

    resource :premiums, only: [:update]
    get 'premiums/payment' => 'premiums#payment'
    get 'premiums/complete' => 'premiums#complete'
  end

  # ========= 管理者(admin)のルーティング ================
  namespace :admin do
    root to: 'homes#top'
    resources :post_recipes, only: [:index, :show, :destroy]
    resources :form_inquiries, only: [:index, :show, :update]
    resources :chats, only: [:index, :show, :create]
    resources :users, only: [:index, :show, :edit, :update]
  end
end

app/views/layouts/_error_messages.html.erb
<% if obj.errors.include?(column) %>
  <ul class="error_explanation">
    <% obj.errors.full_messages_for(column).each do |message| %>
      <li class="text-danger small mt-1 ml-4"><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_flash.html.erb
<!------------ フラッシュメッセージ ------------->

<% if flash[:notice] %>
  <p id="notice" class="pl-4 py-1"><i class="far fa-check-circle pr-2"></i><%= flash[:notice] %></p>
<% elsif flash[:alert] %>
  <p id="alert" class="pl-4 py-1"><i class="fas fa-exclamation-triangle pr-2"></i><%= flash[:alert] %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">

    <div class="row">
      <% if not user_signed_in? || admin_signed_in? %>
        <span class="move-top" id="move-top-guest-btn">
          <%= link_to "ゲストログイン（会員）", users_guest_sign_in_path, method: :post, class:'btn btn-guest-user py-1' %>
        </span>
        <span class="move-top" id="move-top-admin-btn">
          <%= link_to "ゲストログイン（管理者）", admin_guest_sign_in_path, method: :post, class:'btn btn-guest-admin py-1' %>
        </span>
      <% end %>
      <span class="move-top" id="move-top-arrow">
        <%= link_to (image_tag 'arrow.png', size:'50x50'), href:"#" %>
      </span>
    </div>

    <div class="row">
      <div class="mx-auto mt-3 text-center d-flex">
          <%= link_to "Be the Veggie, Green your Life", root_path, class:'mb-2' %>
          <% if not admin_signed_in? %>
            <%= link_to "", form_inquiries_path, class:'fas fa-envelope m-0 pl-2 pt-1' %>
          <% end %>
      </div>
    </div>

    <div class="row">
      <div class="mx-auto">
        <p id="copyright">Copyright © VEGECOOK All Rights Reserved</p>
      </div>
    </div>

</footer>

app/views/layouts/_header.html.erb
<!---------------------- HEADER ------------------------>

<header class="sticky-top shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light py-3">
    <div class="container-fluid px-2">
      <!--<div class='row'>-->

      <!------ Navbar Brand ------>
      <% if admin_signed_in? %>
        <a class="navbar-brand" href="/admin">
          <h4 class="logo-font align-center ml-3 mb-0 pt-2">VegeCook</h4>
        </a>
      <% else %>
        <a class="navbar-brand" href="/">
          <h4 class="logo-font align-center ml-3 mb-0 pt-2">VegeCook</h4>
        </a>
      <% end %>

      <!------- 検索窓 -------->
      <div id="search-window">
      <% if not admin_signed_in? %>
        <%= search_form_for @search, url: post_recipes_searches_path do |f| %>
          <%= f.search_field :title_cont, placeholder: 'レシピを検索', class: 'input ml-4', size: '22' %>
          <%= f.submit "GO!", class:'rounded-pill', id:'search-btn' %>
        <% end %>
      <% end %>
      </div>

      <!----- Collapse Button ----->
      <button class="navbar-toggler toggler-example humberger" type="button" data-toggle="collapse" data-target="#navbarTabContent" aria-controls="navbarTabContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="dark-blue-text">
          <i class="fas fa-bars fa-1x"></i>
        </span>
      </button>

      <!---- Collapsible Content ------->
      <div class="collapse navbar-collapse" id="navbarTabContent">
        <ul class="navbar-nav ml-auto mt-3">

        <!-- 管理者がログインしている場合-->
        <% if admin_signed_in? %>
          <li class="nav-item ml-5"><%= link_to "レシピ一覧", admin_post_recipes_path, class: 'nav-link' %></li>
          <li class="nav-item ml-5"><%= link_to "会員一覧", admin_users_path, class: 'nav-link' %></li>
          <li class="nav-item ml-5"><%= link_to "フォーム", admin_form_inquiries_path , class: 'nav-link' %></li>
          <li class="nav-item ml-5"><%= link_to "チャット", admin_chats_path, class: 'nav-link' %></li>
          <li class="nav-item ml-5"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link' %></li>

        <!--ユーザー（会員）がログインしている場合 -->
        <% elsif user_signed_in? %>
          <li class="nav-item dropdown nav-link ml-5">
            <a class="dropdown-toggle" href="/about" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              ABOUT
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/about"><p class="jp-font-pop m-0">はじめての方</p></a>
              <a class="dropdown-item" href="/premium"><p class="jp-font-pop m-0">プレミアム・プランのご案内</p></a>
              <a class="dropdown-item" href="/form_inquiries"><p class="jp-font-pop m-0">お問い合わせ</p></a>
            </div>
          </li>
          <li class="nav-item ml-5 d-flex">
            <%= link_to (attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpg', fallback: 'no_profile_image.jpg', size:'25x25', class:'mt-2 rounded-circle'), user_path(current_user.id) %>
            <%= link_to "MY PAGE", user_path(current_user.id), class: 'nav-link ml-2' %>
          </li>
          <li class="nav-item ml-5"><%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: 'nav-link' %></li>

        <!-- ログインしていない場合 -->
        <% else %>
          <li class="nav-item ml-5 dropdown nav-link">
            <a class="dropdown-toggle" href="/about" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              ABOUT
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/about"><p class="jp-font-pop m-0">はじめての方</p></a>
              <a class="dropdown-item" href="/premium"><p class="jp-font-pop m-0">プレミアム・プランのご案内</p></a>
              <a class="dropdown-item" href="/form_inquiries"><p class="jp-font-pop m-0">お問い合わせ</p></a>
            </div>
          </li>
          <li class="nav-item ml-5"><%= link_to "SIGN UP", new_user_registration_path, class: 'nav-link' %></li>
          <li class="nav-item ml-5"><%= link_to "LOG IN", new_user_session_path, class: 'nav-link' %></li>
        <% end %>
        </ul>
      </div>

      <!--</div>-->
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vegecook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>
    <script src="https://kit.fontawesome.com/d64cb48cf6.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <div id='footer-position'>
      <main>
        <%= render 'layouts/header' %>
        <%= render 'layouts/flash' %>
        <%= breadcrumbs separator: " &rsaquo; ", class:'text-warning', id:'breadcrumbs-style' %>
        <%= yield %>
        <%= render 'layouts/footer' %>
      </main>
    </div>
  </body>
</html>